sonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
sonar.organization=${{ secrets.SONAR_ORGANIZATION }}

# Analysis path
sonar.sources=.
sonar.language=python
sonar.python.version=3

# Exclude folders that don't need scanning (like migrations or tests)
sonar.exclusions=**/migrations/**, **/tests/**